---
name: ci

"on": [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
          >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push master
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/fred-drake/git-sync:latest
        if: steps.extract_branch.outputs.branch == 'main'

      - name: Build and push version
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: >-
            ghcr.io/fred-drake/git-sync:
            ${{ steps.extract_branch.outputs.branch }}
        if: steps.extract_branch.outputs.branch != 'main'
